# Generated by Django 5.0.4 on 2024-05-03 03:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_item', models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('KITNET', 'KITNET'), ('CASA', 'CASA'), ('CHACARA', 'CHACARA')], max_length=100)),
                ('endereco', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alugado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images', verbose_name='images')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_imovel', to='myapp.imovel')),
            ],
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início')),
                ('data_final', models.DateTimeField(verbose_name='fim')),
                ('criacao', models.DateField(blank=True, default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_locacao', to='myapp.imovel')),
            ],
            options={
                'verbose_name': 'Registrar Locação',
                'verbose_name_plural': 'Registrar Locação',
                'ordering': ['-id'],
            },
        ),
    ]
