# Generated by Django 5.0.4 on 2024-05-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imovel_imagemimovel_rename_clientes_cliente_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='alugado',
            field=models.BooleanField(default=False, verbose_name='Alugado?'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Código do Imóvel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo_item',
            field=models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('KITNET', 'KITNET'), ('CASA', 'CASA'), ('CHACARA', 'CHACARA')], max_length=100, verbose_name='Tipo do Imóvel'),
        ),
        migrations.CreateModel(
            name='ImovelImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='images')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_imovel', to='myapp.imovel')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagemImovel',
        ),
    ]
