# Generated by Django 5.0.4 on 2024-05-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_imovel_alugado_alter_imovel_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelimagem',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='imovelimagem',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imovel_imagem', to='myapp.imovel'),
        ),
    ]
