# Generated by Django 5.0.4 on 2024-05-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sobre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Página Sobre Nós', 'verbose_name_plural': 'Sobre'},
        ),
        migrations.AddField(
            model_name='sobre',
            name='ativado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='texto',
            field=models.TextField(),
        ),
    ]
